workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60

    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BASE_URL: $BASE_URL

    scripts:
      - name: Post clone script (create production.env)
        script: |
          echo "Creating production.env from Codemagic environment variable..."
          mkdir -p conf
          echo "$BASE_URL" > conf/production.env
          echo "production.env created at conf/production.env"

      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build Android AAB (production)
        script: |
          flutter build appbundle \
            --release \
            --flavor production \
            -t lib/main_production.dart

      - name: Build iOS (production)
        script: |
          flutter build ipa \
            --release \
            --flavor production \
            -t lib/main_production.dart

    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      - build/**/mapping.txt

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store: false

      email:
        recipients:
          - agusdharmaudel@gmail.com
        notify:
          success: true
          failure: true
